version: '2'

services:
  api_nginx:
    image: nginx:stable
    networks:
      - api
    ports:
      - "8000:80"
    volumes_from:
      - api_phpfpm
    volumes:
      - ./docker/nginx/sites.conf:/etc/nginx/conf.d/default.conf:cached
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:cached
    working_dir: /etc/nginx/conf.d
    logging:
      driver: none

  api_phpfpm:
    build:
      context: ./docker/phpfpm
    expose:
      - 9000
    networks:
      - api
    volumes:
      - .:/var/www/api:cached
      - ./docker/phpfpm/php.timezone.ini:/usr/local/etc/php/conf.d/timezone.ini:cached
      - ./docker/phpfpm/php.error.ini:/usr/local/etc/php/conf.d/error.ini:cached
      - ./docker/phpfpm/php.xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:cached
    working_dir: /var/www/api
    environment:
      - XDEBUG_CONFIG=remote_host=docker.for.mac.localhost
networks:
  api:
    driver: bridge
